from django.urls import path
from api.views import core_views as views

urlpatterns = [
    path('uv/', views.UVListCreateAPIViw.as_view()),
    path('uv/<int:pk>/', views.UVDetailAPIViw.as_view()),
    path('uv/update/<int:pk>/', views.UVUpdateAPIViw.as_view()),
    path('uv/delete/<int:pk>/', views.UVDeleteAPIViw.as_view()),
    path('callesindependencia/', views.CallesIndependenciaListCreateAPIViw.as_view()),
    path('callesindependencia/<int:pk>/', views.CallesIndependenciaDetailAPIViw.as_view()),
    path('callesindependencia/update/<int:pk>/', views.CallesIndependenciaUpdateAPIViw.as_view()),
    path('callesindependencia/delete/<int:pk>/', views.CallesIndependenciaDeleteAPIViw.as_view()),
    path('persona/', views.PersonaListCreateAPIViw.as_view()),
    path('persona-lista/', views.PersonaList2CreateAPIViw.as_view()),
    path('persona/<int:pk>/', views.PersonaDetailAPIViw.as_view()),
    path('persona/update/<int:pk>/', views.PersonaUpdateAPIViw.as_view()),
    path('persona/delete/<int:pk>/', views.PersonaDeleteAPIViw.as_view()),
    path('telefono/', views.TelefonoListCreateAPIViw.as_view()),
    path('telefono/<int:pk>/', views.TelefonoDetailAPIViw.as_view()),
    path('telefono-by-persona/<int:persona>/', views.TelefonoDetailByPersonaAPIViw.as_view()),
    path('telefono/update/<int:pk>/', views.TelefonoUpdateAPIViw.as_view()),
    path('telefono/delete/<int:pk>/', views.TelefonoDeleteAPIViw.as_view()),
    path('correo/', views.CorreoListCreateAPIViw.as_view()),
    path('correo/<int:pk>/', views.CorreoDetailAPIViw.as_view()),
    path('correo-by-persona/<int:persona>/', views.CorreoDetailByPersonaAPIViw.as_view()),
    path('correo/update/<int:pk>/', views.CorreoUpdateAPIViw.as_view()),
    path('correo/delete/<int:pk>/', views.CorreoDeleteAPIViw.as_view()),
    path('direccion/', views.DireccionListCreateAPIViw.as_view()),
    path('direccion/<int:pk>/', views.DireccionDetailAPIViw.as_view()),
    path('direccion-by-persona/<int:persona>/', views.DireccionDetailByPersonaAPIViw.as_view()),
    path('direccion/update/<int:pk>/', views.DireccionUpdateAPIViw.as_view()),
    path('direccion/delete/<int:pk>/', views.DireccionDeleteAPIViw.as_view()),
    path('personainfosalud/', views.PersonaInfoSaludListCreateAPIViw.as_view()),
    path('personainfosalud/<int:pk>/', views.PersonaInfoSaludDetailAPIViw.as_view()),
    path('personainfosalud-by-persona/<int:persona>/', views.PersonaInfoSaludDetailByPersonaAPIViw.as_view()),
    path('personainfosalud/update/<int:pk>/', views.PersonaInfoSaludUpdateAPIViw.as_view()),
    path('personainfosalud/delete/<int:pk>/', views.PersonaInfoSaludDeleteAPIViw.as_view()),
    path('personaarchivos/', views.PersonaArchivosListCreateAPIViw.as_view()),
    path('personaarchivos/<int:pk>/', views.PersonaArchivosDetailAPIViw.as_view()),
    path('personaarchivos/update/<int:pk>/', views.PersonaArchivosUpdateAPIViw.as_view()),
    path('personaarchivos/delete/<int:pk>/', views.PersonaArchivosDeleteAPIViw.as_view()),
]