# Generated by Django 4.1.5 on 2023-01-30 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallesIndependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Calle ',
                'verbose_name_plural': 'Calles de Independencia',
                'ordering': ['calle'],
            },
        ),
        migrations.CreateModel(
            name='CargaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_producto', models.FileField(blank=True, null=True, upload_to='farmacia/carga_producto/')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionDelito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Clasificacion de delito')),
            ],
            options={
                'verbose_name': 'Clasificación del delito',
                'verbose_name_plural': 'Clasificaciones de los delitos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.FileField(blank=True, null=True, upload_to='farmacia/receta_medica/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Comprobante Venta',
                'verbose_name_plural': 'Comprobantes de Venta',
            },
        ),
        migrations.CreateModel(
            name='Delito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Delito')),
                ('clasificacion_delito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.clasificaciondelito', verbose_name='Clasificacion del delito')),
            ],
            options={
                'verbose_name': 'Delito',
                'verbose_name_plural': 'Delitos',
                'ordering': ['clasificacion_delito', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Denunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono denunciante')),
                ('correo', models.EmailField(blank=True, max_length=40, null=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Denunciante',
                'verbose_name_plural': 'Denunciantes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Laboratorio')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='LlamadoSeguridad',
            fields=[
                ('numero_requerimiento', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de requerimiento')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Llamado seguridad',
                'verbose_name_plural': 'Llamados de seguridad',
                'ordering': ['numero_requerimiento'],
            },
        ),
        migrations.CreateModel(
            name='OrdenIngresoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado Ingreso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('farmaceuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Orden de Ingreso de Producto',
                'verbose_name_plural': 'Ordenes de Ingresos de Productos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('RUT', 'Rut'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='RUT', max_length=200, verbose_name='Tipo de Documento')),
                ('numero_identificacion', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Número de Identidad')),
                ('nombre_persona', models.CharField(max_length=200, verbose_name='Nombre Persona')),
                ('apellido_paterno', models.CharField(max_length=200, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=200, verbose_name='Apellido Materno')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEO/A', 'Soltero/a'), ('CASADO/A', 'Casado/a'), ('VIUDO/A', 'Viudo/a'), ('UNION CIVIL', 'Union Civil'), ('DIVORSIADO/A', 'Divorsiado/a')], default='MOVIL', max_length=200, null=True, verbose_name='Estado Civil')),
                ('hijos', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Hijos')),
                ('nacionalidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nacionalidad')),
                ('enfermedad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enfermedad')),
                ('medicamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Medicamento')),
                ('lugar_de_atencion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar De Atencion')),
                ('discapacidad', models.BooleanField(blank=True, default=False, null=True, verbose_name='Discapacidad')),
                ('certificado_compin', models.BooleanField(blank=True, default=False, null=True, verbose_name='Certificado Compin')),
                ('embarazo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Embarazo')),
                ('certificado_embarazo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Certificado Embarazo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ProductoFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_producto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Producto')),
                ('proveedor', models.CharField(blank=True, max_length=25, null=True, verbose_name='Proveedor')),
                ('p_a', models.CharField(blank=True, max_length=200, null=True, verbose_name='Componente Activo')),
                ('dosis', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dosis del Producto')),
                ('presentacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Presentacion del Producto')),
                ('precio', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Precio Producto')),
                ('cenabast', models.BooleanField(blank=True, default=False, null=True, verbose_name='Cenabast')),
                ('bioequivalencia', models.BooleanField(blank=True, default=False, null=True, verbose_name='Bioequivalencia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.laboratorios', verbose_name='Laboratorio')),
            ],
            options={
                'verbose_name': 'Producto Farmacia',
                'verbose_name_plural': 'Productos de Farmacia',
                'ordering': ['marca_producto', 'dosis'],
            },
        ),
        migrations.CreateModel(
            name='UV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_uv', models.PositiveIntegerField(verbose_name='Número de U.V.')),
            ],
            options={
                'verbose_name': 'Unidad Vecinal',
                'verbose_name_plural': 'Unidades Vecinales',
                'ordering': ['numero_uv'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono')),
                ('telefono_secundario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono Secundario')),
                ('tipo_telefono', models.CharField(choices=[('MOVIL', 'Movil'), ('CASA', 'Casa'), ('TRABAJO', 'Trabajo'), ('OTRO', 'Otro')], default='MOVIL', max_length=200, null=True, verbose_name='Tipo de Teléfono')),
                ('tipo_telefono_secundario', models.CharField(choices=[('MOVIL', 'Movil'), ('CASA', 'Casa'), ('TRABAJO', 'Trabajo'), ('OTRO', 'Otro'), ('NO APLICA', 'No Aplica')], default='NO APLICA', max_length=200, null=True, verbose_name='Tipo de Teléfono Secundario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Teléfono Persona',
                'verbose_name_plural': 'Teléfonos Personas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('1', 'Recepcionado'), ('2', 'Pendiente'), ('3', 'En Curso'), ('4', 'Resuelto')], default='1', max_length=1, verbose_name='Estatus')),
                ('via_ingreso', models.CharField(choices=[('1', 'Fono 1469'), ('2', 'Patrullaje Preventivo'), ('3', 'Patrullaje colaborativo (carabineros)'), ('4', 'Demanda espontánea'), ('5', 'Fiscalización'), ('6', 'Otro:_____')], default='1', max_length=1, verbose_name='Vía de Ingreso')),
                ('via_ingreso_otro', models.CharField(blank=True, max_length=200, null=True, verbose_name=' ')),
                ('delito_otro', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('calle', models.CharField(max_length=200, verbose_name='Avenida/Calle/Pasaje')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numeración')),
                ('complemento_direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento de Dirección')),
                ('interseccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intersección')),
                ('prioridad', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=1, verbose_name='Prioridad')),
                ('resolucion', models.CharField(choices=[('1', 'Cursar infracción'), ('2', 'Proceso judicial'), ('3', 'Derivación Área Prevención'), ('4', 'Territorial'), ('5', 'Atención a Víctimas'), ('6', 'Convivencia'), ('7', 'Derivación Unidad especializada'), ('8', 'Intramunicipal ¿cuál?'), ('9', 'Extramunicipal ¿cuál?')], default='1', max_length=1, verbose_name='Forma de resolución del requerimiento')),
                ('resolucion_otro', models.CharField(blank=True, max_length=50, null=True, verbose_name='¿Cuál?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('delito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.delito', verbose_name='Delito')),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.denunciante', verbose_name='denunciante')),
                ('numero_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.llamadoseguridad', verbose_name='Número de requerimiento')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.uv', verbose_name='Unidad Vecinal')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['numero_requerimiento'],
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receta', models.FileField(blank=True, null=True, upload_to='farmacia/receta_medica/%Y/%m/%d/')),
                ('comprobante_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.comprobanteventa', verbose_name='Venta asociada')),
            ],
            options={
                'verbose_name': 'Receta Medica',
                'verbose_name_plural': 'Recetas Medicas',
            },
        ),
        migrations.CreateModel(
            name='ProductoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Vendida')),
                ('precio_venta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Producto de la Venta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('n_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.comprobanteventa')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Producto Vendido',
                'verbose_name_plural': 'Productos Vendidos',
                'ordering': ['-n_venta'],
            },
        ),
        migrations.CreateModel(
            name='ProductoMermado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Mermada')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('motivo', models.CharField(choices=[('NO ESPECIFICADO', 'No Especificado'), ('VENCIMIENTO', 'Vencimiento'), ('CANJE', 'Canje'), ('DETERIORO', 'Deterioro'), ('MERMA', 'Merma'), ('PRESTAMOS', 'Préstamos'), ('OTRO', 'Otro')], default='NO ESPECIFICADO', max_length=100, verbose_name='Motivo')),
                ('farmaceuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Producto Mermado',
                'verbose_name_plural': 'Productos Mermados',
            },
        ),
        migrations.CreateModel(
            name='ProductoIngresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada al Stock')),
                ('lote', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de Lote')),
                ('precio_compra', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Compra Producto')),
                ('precio_venta', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Venta Producto')),
                ('n_factura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de factura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('n_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ordeningresoproducto')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Producto Ingresado',
                'verbose_name_plural': 'Productos Ingresados',
                'ordering': ['-n_venta'],
            },
        ),
        migrations.CreateModel(
            name='PersonaInfoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevision', models.CharField(choices=[('FONASA', 'Fonasa'), ('DIPRECA-CAPREDENA', 'Dipreca-Capredena'), ('ISAPRE', 'Isapre'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=30, verbose_name='Prevision de Salud')),
                ('isapre', models.CharField(choices=[('NO APLICA', 'No Aplica'), ('BANMEDICA', 'Banmedica'), ('ISALUD', 'Isalud'), ('COLMENA', 'Colmena'), ('CONSALUD', 'Consalud'), ('CRUZBLANCA', 'Cruz Blanca'), ('CRUZ DEL NORTE', 'Cruz del Norte'), ('NUEVA MASVIDA', 'Nueva Masvida'), ('FUNDACION', 'Fundacion'), ('VIDA TRES', 'Vida Tres'), ('ESENCIAL', 'Esencial')], default='NO APLICA', max_length=30, null=True, verbose_name='Isapre')),
                ('comentarios', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentarios ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Informacion de salud Persona',
                'verbose_name_plural': 'Informacion de salud Personas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='PersonaArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_personas/%Y/%m/%d/')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Archivo de persona',
                'verbose_name_plural': 'Archivos de persona',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='uv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.uv', verbose_name='Unidad Vecinal'),
        ),
        migrations.CreateModel(
            name='OrdenIngresoLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingresada', models.PositiveIntegerField(default=1, verbose_name='Cantidad Ingresada al Stock')),
                ('precio_compra', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Compra Producto')),
                ('precio_venta', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio Venta Producto')),
                ('n_lote', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de Lote')),
                ('n_factura', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numero de factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.productofarmacia', verbose_name='Nombre Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, null=True, verbose_name='Activo')),
                ('calle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Avenida/Calle/Pasaje')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeración')),
                ('complemento_direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento de Dirección')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.persona', verbose_name='Persona')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.uv', verbose_name='UV')),
            ],
            options={
                'verbose_name': 'Dirrecion Persona',
                'verbose_name_plural': 'Direcciones Personas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=40, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Correo Persona',
                'verbose_name_plural': 'Correos Personas',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.persona', verbose_name='Comprador'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='farmaceuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional'),
        ),
        migrations.CreateModel(
            name='BodegaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, null=True, verbose_name='Stock del producto')),
                ('stock_min', models.IntegerField(blank=True, null=True, verbose_name='Stock minimo del producto')),
                ('stock_max', models.IntegerField(blank=True, null=True, verbose_name='Stock maximo del producto')),
                ('holgura', models.IntegerField(blank=True, null=True, verbose_name='Holgura del Stock')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.productofarmacia', verbose_name='Nombre Producto')),
            ],
            options={
                'verbose_name': 'Bodega Virtual',
                'verbose_name_plural': 'Bodega Virtual',
                'db_table': 'BodegaVirtual',
            },
        ),
    ]
