# Generated by Django 4.1.5 on 2023-05-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='laboratorio_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='farmacia.laboratorios', verbose_name=' Id Laboratorio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productofarmacia',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Laboratorio'),
        ),
    ]
