# Generated by Django 4.1.5 on 2023-05-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_productofarmacia_laboratorio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteventa',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado venta'),
        ),
    ]
