# Generated by Django 4.1.5 on 2023-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_comprobanteventa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteventa',
            name='estado',
            field=models.CharField(blank=True, choices=[('EN PROGRESO', 'En Progreso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='EN PROGRESO', max_length=30, null=True, verbose_name='Estado de venta'),
        ),
    ]
