# Generated by Django 4.1.5 on 2024-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_alter_comprobanteventa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='fact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fact'),
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='forma_farmaceutica',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma Farmaceutica'),
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='precio_sin_iva',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Sin Iva'),
        ),
        migrations.AddField(
            model_name='productofarmacia',
            name='registro_sanitario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro Sanitario'),
        ),
    ]
