# Generated by Django 4.1.5 on 2024-02-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_productofarmacia_fact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Recepcion'),
        ),
    ]
