# Generated by Django 4.1.5 on 2024-02-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_productofarmacia_fecha_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofarmacia',
            name='estado',
            field=models.CharField(blank=True, choices=[('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('INGRESANDO', 'Ingresando')], default='ACEPTADO', max_length=30, null=True),
        ),
    ]
