# Generated by Django 4.1.5 on 2023-03-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='uv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal'),
        ),
    ]
