# Generated by Django 4.1.5 on 2023-04-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_persona_nombre_completo_alter_persona_uv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesIndependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=200)),
                ('conjunto', models.CharField(max_length=200)),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.callesindependencia', verbose_name='Calles de Independencia')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecial')),
            ],
        ),
    ]
