# Generated by Django 4.1.5 on 2023-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_persona_nombre_completo_alter_persona_uv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correo',
            name='correo',
            field=models.EmailField(blank=True, max_length=40, null=True, verbose_name='Email'),
        ),
    ]
