# Generated by Django 4.1.5 on 2023-04-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_correo_correo'),
        ('core', '0003_condicionesindependencia'),
    ]

    operations = [
    ]
