# Generated by Django 4.1.5 on 2023-05-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20230422_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido Paterno'),
        ),
    ]
