# Generated by Django 4.1.5 on 2023-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_persona_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTEO/A', 'Soltero/a'), ('CASADO/A', 'Casado/a'), ('VIUDO/A', 'Viudo/a'), ('UNION CIVIL', 'Union Civil'), ('DIVORCIADO/A', 'Divorciado/a')], default='MOVIL', max_length=200, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='personainfosalud',
            name='isapre',
            field=models.CharField(choices=[('NO APLICA', 'No Aplica'), ('BANMEDICA', 'Banmedica'), ('ISALUD', 'Isalud'), ('COLMENA', 'Colmena'), ('CONSALUD', 'Consalud'), ('CRUZ BLANCA', 'Cruz Blanca'), ('CRUZ DEL NORTE', 'Cruz del Norte'), ('NUEVA MASVIDA', 'Nueva Masvida'), ('FUNDACION', 'Fundacion'), ('VIDA TRES', 'Vida Tres'), ('ESENCIAL', 'Esencial')], default='NO APLICA', max_length=30, null=True, verbose_name='Isapre'),
        ),
    ]
