# Generated by Django 4.1.5 on 2023-06-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_persona_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='core.persona', verbose_name='Persona'),
        ),
    ]
