# Generated by Django 4.1.5 on 2023-07-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_direccion_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoblacionUV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Poblacion Total')),
                ('hombres', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hombres Total')),
                ('mujeres', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mujeres Total')),
                ('porcentaje_inmigrante', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje Poblacion Inmigrante')),
                ('superficie_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Superficie Total m2')),
                ('superficie_no_habitada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Superficie no habitadas m2')),
                ('superficie', models.PositiveIntegerField(blank=True, null=True, verbose_name='Superficie m2')),
                ('densidad_habitantekm2', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Densidad Habitante/Km2')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uv', verbose_name='UV')),
            ],
        ),
    ]
