# Generated by Django 4.1.5 on 2024-01-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_poblacionuv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_carga/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Archivo de carga',
                'verbose_name_plural': 'Archivos de carga',
            },
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO/A', 'Soltero/a'), ('CASADO/A', 'Casado/a'), ('VIUDO/A', 'Viudo/a'), ('UNION CIVIL', 'Union Civil'), ('DIVORCIADO/A', 'Divorciado/a')], default='MOVIL', max_length=200, null=True, verbose_name='Estado Civil'),
        ),
    ]
