# Generated by Django 4.1.5 on 2023-07-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_alter_direccion_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=40, verbose_name='Categoria de GSL')),
            ],
            options={
                'verbose_name': 'Categoria de GSL',
                'verbose_name_plural': 'Categorias de GSL',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategoriaGSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subcategoria', models.CharField(max_length=40, verbose_name='Subcategoria de GSL')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='gsl.categoriagsl')),
            ],
            options={
                'verbose_name': 'Subcategoria de GSL',
                'verbose_name_plural': 'Subcategorias de GSL',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GSL',
            fields=[
                ('importID', models.IntegerField(primary_key=True, serialize=False)),
                ('RUN', models.IntegerField(blank=True, null=True)),
                ('ID_CIUDADANO_SIN_RSH', models.IntegerField(blank=True, null=True)),
                ('Beneficios_o_Servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha_de_Compromiso', models.DateField(blank=True, null=True)),
                ('Fecha_decreto', models.DateField(blank=True, null=True)),
                ('Monto', models.IntegerField(blank=True, null=True)),
                ('Estado', models.IntegerField(blank=True, null=True)),
                ('CALLE', models.CharField(blank=True, max_length=255, null=True)),
                ('Numero_calle_RSH', models.CharField(blank=True, max_length=255, null=True)),
                ('Cod_region_GSL', models.IntegerField(blank=True, null=True)),
                ('Cod_comuna_GSL', models.IntegerField(blank=True, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsl.categoriagsl', verbose_name='categoria GSL')),
                ('Subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gsl.subcategoriagsl', verbose_name='subcategoria GSL')),
                ('UV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.uv', verbose_name='UV')),
            ],
        ),
    ]
