# Generated by Django 4.1.5 on 2023-06-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransitoDataLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv', models.IntegerField()),
                ('licencia_conducir', models.IntegerField()),
                ('permiso_circulacion', models.IntegerField()),
                ('rank_licencia_conducir', models.IntegerField(blank=True, null=True)),
                ('rank_permiso_circulacion', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('api_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_lab.apicall')),
            ],
        ),
        migrations.CreateModel(
            name='ImpuestosYDerechosDataLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv', models.IntegerField()),
                ('total', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('comercial', models.IntegerField()),
                ('profesional', models.IntegerField()),
                ('industrial', models.IntegerField()),
                ('microempresa', models.IntegerField()),
                ('estacionada', models.IntegerField()),
                ('rank_total', models.IntegerField(blank=True, null=True)),
                ('rank_alcohol', models.IntegerField(blank=True, null=True)),
                ('rank_comercial', models.IntegerField(blank=True, null=True)),
                ('rank_profesional', models.IntegerField(blank=True, null=True)),
                ('rank_industrial', models.IntegerField(blank=True, null=True)),
                ('rank_microempresa', models.IntegerField(blank=True, null=True)),
                ('rank_estacionada', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('api_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_lab.apicall')),
            ],
        ),
        migrations.CreateModel(
            name='FarmaciaDataLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventas', models.IntegerField()),
                ('rank_ventas', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('api_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_lab.apicall')),
            ],
        ),
        migrations.CreateModel(
            name='DOMDataLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv', models.IntegerField()),
                ('total', models.IntegerField()),
                ('anexion', models.IntegerField()),
                ('antiguas', models.IntegerField()),
                ('anulacion', models.IntegerField()),
                ('cambio_de_destino', models.IntegerField()),
                ('fusion', models.IntegerField()),
                ('ley_20898', models.IntegerField()),
                ('obras_menores', models.IntegerField()),
                ('permisos_de_edificacion', models.IntegerField()),
                ('recepcion_final', models.IntegerField()),
                ('regularizaciones', models.IntegerField()),
                ('regularizaciones_ley_18591', models.IntegerField()),
                ('resolucion', models.IntegerField()),
                ('subdivisiones', models.IntegerField()),
                ('ventas_por_piso', models.IntegerField()),
                ('rank_total', models.IntegerField(blank=True, null=True)),
                ('rank_anexion', models.IntegerField(blank=True, null=True)),
                ('rank_antiguas', models.IntegerField(blank=True, null=True)),
                ('rank_anulacion', models.IntegerField(blank=True, null=True)),
                ('rank_cambiodestino', models.IntegerField(blank=True, null=True)),
                ('rank_fusion', models.IntegerField(blank=True, null=True)),
                ('rank_ley20898', models.IntegerField(blank=True, null=True)),
                ('rank_obrasmenores', models.IntegerField(blank=True, null=True)),
                ('rank_permisosedificacion', models.IntegerField(blank=True, null=True)),
                ('rank_recepcionfinal', models.IntegerField(blank=True, null=True)),
                ('rank_regularizaciones', models.IntegerField(blank=True, null=True)),
                ('rank_regularizaciones18591', models.IntegerField(blank=True, null=True)),
                ('rank_resolucion', models.IntegerField(blank=True, null=True)),
                ('rank_subdivisiones', models.IntegerField(blank=True, null=True)),
                ('rank_ventasporpiso', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('api_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_lab.apicall')),
            ],
        ),
    ]
