# Generated by Django 4.1.5 on 2023-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='tipo_call',
            field=models.CharField(blank=True, choices=[('FARMACIA', 'Farmacia'), ('SEGURIDAD', 'Seguridad'), ('DIMAP', 'Dimap'), ('IMPUESTOS Y DERECHOS', 'Impuestos y derechos'), ('AYUDA SOCIAL', 'Ayuda social'), ('EXCENCION BASURA', 'Excencion basura'), ('DOM', 'Dom'), ('TRANSITO', 'Transito')], max_length=200, null=True, verbose_name='Origen del llamado'),
        ),
    ]
