from django.urls import path
from api.views import core_views as views

urlpatterns = [
    path('uv/', views.UVListCreateAPIViw.as_view()),
    path('uv/<int:pk>/', views.UVDetailAPIViw.as_view()),
    path('uv/<int:pk>/update/', views.UVUpdateAPIViw.as_view()),
    path('uv/<int:pk>/delete/', views.UVDeleteAPIViw.as_view()),
    path('callesindependencia/', views.get_data_calles_independencia),
    path('callesindependencia/<int:pk>/', views.get_data_uv),
    path('callesindependencia/<int:pk>/update/', views.get_data_uv),
    path('callesindependencia/<int:pk>/delete/', views.get_data_uv),
    path('persona/', views.get_data_persona),
    path('persona/<int:pk>/', views.get_data_uv),
    path('persona/<int:pk>/update/', views.get_data_uv),
    path('persona/<int:pk>/delete/', views.get_data_uv),
    path('telefono', views.get_data_telefono),
    path('telefono/<int:pk>/', views.get_data_uv),
    path('telefono/<int:pk>/update/', views.get_data_uv),
    path('telefono/<int:pk>/delete/', views.get_data_uv),
    path('correo/', views.get_data_correo),
    path('correo/<int:pk>/', views.get_data_uv),
    path('correo/<int:pk>/update/', views.get_data_uv),
    path('correo/<int:pk>/delete/', views.get_data_uv),
    path('direccion/', views.get_data_direccion),
    path('direccion/<int:pk>/', views.get_data_uv),
    path('direccion/<int:pk>/update/', views.get_data_uv),
    path('direccion/<int:pk>/delete/', views.get_data_uv),
    path('personainfosalud/', views.get_data_persona_info_salud),
    path('personainfosalud/<int:pk>/', views.get_data_uv),
    path('personainfosalud/<int:pk>/update/', views.get_data_uv),
    path('personainfosalud/<int:pk>/delete/', views.get_data_uv),
    path('datapersonaarchivos/', views.get_data_persona_archivos),
    path('datapersonaarchivos/<int:pk>/', views.get_data_uv),
    path('datapersonaarchivos/<int:pk>/update/', views.get_data_uv),
    path('datapersonaarchivos/<int:pk>/delete/', views.get_data_uv),
]