# Generated by Django 4.1.5 on 2023-01-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallesIndependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Calle ',
                'verbose_name_plural': 'Calles de Independencia',
                'ordering': ['calle'],
            },
        ),
        migrations.CreateModel(
            name='UV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_uv', models.PositiveIntegerField(verbose_name='Número de U.V.')),
            ],
            options={
                'verbose_name': 'Unidad Vecinal',
                'verbose_name_plural': 'Unidades Vecinales',
                'ordering': ['numero_uv'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('RUT', 'Rut'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='RUT', max_length=200, verbose_name='Tipo de Documento')),
                ('numero_identificacion', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Número de Identidad')),
                ('nombre_persona', models.CharField(max_length=200, verbose_name='Nombre Persona')),
                ('apellido_paterno', models.CharField(max_length=200, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=200, verbose_name='Apellido Materno')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEO/A', 'Soltero/a'), ('CASADO/A', 'Casado/a'), ('VIUDO/A', 'Viudo/a'), ('UNION CIVIL', 'Union Civil'), ('DIVORSIADO/A', 'Divorsiado/a')], default='MOVIL', max_length=200, null=True, verbose_name='Estado Civil')),
                ('hijos', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Hijos')),
                ('nacionalidad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nacionalidad')),
                ('enfermedad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enfermedad')),
                ('medicamento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Medicamento')),
                ('lugar_de_atencion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar De Atencion')),
                ('discapacidad', models.BooleanField(blank=True, default=False, null=True, verbose_name='Discapacidad')),
                ('certificado_compin', models.BooleanField(blank=True, default=False, null=True, verbose_name='Certificado Compin')),
                ('embarazo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Embarazo')),
                ('certificado_embarazo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Certificado Embarazo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['created'],
            },
        ),
    ]
