# Generated by Django 4.1.5 on 2023-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_legacy', '0003_dom_empresas_entregaspandemia_exencionaseo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exencionaseo',
            name='tramo_rsh',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tramo RSH'),
        ),
    ]
