# Generated by Django 4.1.5 on 2024-02-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_archivocarga_alter_persona_estado_civil'),
        ('mapa_legacy', '0005_empresas_monto_empresas_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionSocialLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Asociada')),
                ('calle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Avenida/Calle/Pasaje')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numeración')),
                ('tipo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria')),
                ('beneficio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Beneficio')),
                ('periodo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de periodo')),
                ('tipo_caso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo Caso GSL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('uv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uv', verbose_name='Unidad Vecinal')),
            ],
        ),
    ]
