# Generated by Django 4.1.5 on 2024-03-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_legacy', '0006_gestionsociallocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionsociallocal',
            name='numero',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Numeración'),
        ),
    ]
